-- Create the users table
CREATE TABLE public.users (
  id UUID NOT NULL PRIMARY KEY REFERENCES auth.users(id),
  name TEXT,
  role TEXT,
  email TEXT
);

-- Create the classes table
CREATE TABLE public.classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  teacher_id UUID REFERENCES public.users(id)
);

-- Create the students table
CREATE TABLE public.students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  class_id BIGINT REFERENCES public.classes(id)
);

-- Create the teachers table
CREATE TABLE public.teachers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT
);

-- Create the attendance table
CREATE TABLE public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES public.students(id),
  date DATE NOT NULL,
  status TEXT NOT NULL,
  class_id BIGINT REFERENCES public.classes(id)
);

-- Create the marks table
CREATE TABLE public.marks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES public.students(id),
  subject TEXT NOT NULL,
  marks INTEGER
);

-- Create the announcements table
CREATE TABLE public.announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  created_by UUID REFERENCES public.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
